# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env

  redis:
    image: redis
    ports:
      - 6379:6379

  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   env_file: .env

  # celery:
  #   build:
  #     context: .
  #     dockerfile: celery.dockerfile
  #   command: celery -A Task worker --beat --scheduler django --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     - redis
  #   env_file: .env

